version: '3'

services:
  www:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: madlibs_ai
    container_name: madlibs_ai
    volumes:
      - ./backend/madlibs_ai:/code/madlibs_ai
      - ./backend/apps:/code/apps
      # - ./.var/media:/srv/media  # Media files
    command: gunicorn madlibs_ai.wsgi:application --bind 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env  
#   db:
#     image: postgres
#     container_name: madlibs-db
#     environment:
#         POSTGRES_PASSWORD: root
#         POSTGRES_DB: madlibs_ai
#     volumes:
#       - db-data:/var/lib/postgresql/data 
#     ports:
#       - 5432:5432
#     env_file:
#       - .env

# volumes:
#   db-data:
