version: '3.8'

services:
  madlibs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: gunicorn --bind :8000 --workers 2 madlibs_api.wsgi

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 5173:5173

  db:
    image: postgres
    container_name: madlibs-db
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: madlibs
    volumes:
      - db-data:/var/lib/postgresql/data 
    ports:
      - 5432:5432

volumes:
  db-data: