# fly.toml app configuration file generated for madlibs-api on 2023-09-09T10:17:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "madlibs-api"
primary_region = "sea"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
